version: '3.4'

services:

  db.${BUILD_ID}:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: ./mysql.Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"

  app.${BUILD_ID}:
    image: python:latest
    restart: always
    build:
      context: .
      dockerfile: ./app.Dockerfile
    ports:
      - 5000:5000