version: '3.4'

services:

  db:
    image: zmbrahian/${COMPOSE_PROJECT_NAME}-db:${BUILD_ID}
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: ./mysql.Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"

  app:
    image: zmbrahian/${COMPOSE_PROJECT_NAME}-app:${BUILD_ID}
    restart: always
    build:
      context: .
      dockerfile: ./app.Dockerfile
    ports:
      - 5000:5000